baseURL = "/"
languageCode = "en-us"
[[menu.main]]
name = "Home"
url = "/"
weight = 1
[[menu.main]]
name = "Our Team"
url = "/teams"
weight = 2
[[menu.main]]
name = "Our Partners"
url = "/partners"
weight = 3
[[menu.main]]
name = "Listings"
url = "/listings"
weight = 4
